name: pradeep_manchukonda_clock
description: Clock Implementation for Flutter Clock Competition.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  intl: ^0.16.1
  gradient_text: ^1.0.2
  flare_flutter: ^1.8.1
  flutter:
    sdk: flutter
  flutter_clock_helper:
    path: ../flutter_clock_helper
  animated_text_kit: ^2.0.0
  simple_animations: ^1.3.4
  provider: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/flare/clock_comp.flr

  fonts:
    - family: Rajdhani
      fonts:
        - asset: assets/fonts/Rajdhani-Regular.ttf
        - asset: assets/fonts/Rajdhani-medium.ttf
        - asset: assets/fonts/Rajdhani-light.ttf
        - asset: assets/fonts/Rajdhani-Bold.ttf
        - asset: assets/fonts/Rajdhani-SemiBold.ttf
