name: pradeep_manchukonda_clock
description: Clock Implementation for Flutter Competition.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  intl: ^0.16.1
  gradient_text: ^1.0.2
  flare_flutter: ^1.8.1
  flutter:
    sdk: flutter
  flutter_clock_helper:
    path: ../flutter_clock_helper
  auto_size_text: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/flare/clock_comp.flr

  fonts:
    - family: Rajdhani
      fonts:
        - asset: assets/fonts/Rajdhani-Regular.ttf
        - asset: assets/fonts/Rajdhani-medium.ttf
        - asset: assets/fonts/Rajdhani-light.ttf
        - asset: assets/fonts/Rajdhani-Bold.ttf
        - asset: assets/fonts/Rajdhani-SemiBold.ttf

    - family: AdventPro
      fonts:
        - asset: assets/fonts/AdventPro-Regular.ttf
        - asset: assets/fonts/AdventPro-medium.ttf
        - asset: assets/fonts/AdventPro-light.ttf
        - asset: assets/fonts/AdventPro-Bold.ttf
        - asset: assets/fonts/AdventPro-SemiBold.ttf
        - asset: assets/fonts/AdventPro-ExtraLight.ttf

    - family: Economica
      fonts:
        - asset: assets/fonts/Economica-Bold.ttf
        - asset: assets/fonts/Economica-Regular.ttf

    - family: Orbitron
      fonts:
        - asset: assets/fonts/Orbitron-Black.ttf
        - asset: assets/fonts/Orbitron-Medium.ttf
        - asset: assets/fonts/Orbitron-Regular.ttf
        - asset: assets/fonts/Orbitron-Bold.ttf
